# Generated by Django 3.0.6 on 2020-06-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(default=1, max_length=100),
        ),
    ]
