# Generated by Django 3.0.6 on 2020-06-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.RemoveField(
            model_name='content',
            name='order',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
    ]
