# Generated by Django 3.0.6 on 2020-06-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0002_auto_20200620_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='author',
            new_name='username',
        ),
    ]
