# Generated by Django 3.0.6 on 2020-06-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0003_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='user',
            new_name='username',
        ),
    ]
