# Generated by Django 3.0.7 on 2020-06-23 09:44

import content_management_system.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0003_auto_20200620_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=content_management_system.fields.OrderField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=content_management_system.fields.OrderField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
