# Generated by Django 3.0.6 on 2020-06-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0004_auto_20200619_0839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
