# Generated by Django 3.0.6 on 2020-06-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0004_content_file_image_module_text_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(default=1, max_length=2000),
        ),
    ]
