# Generated by Django 3.0.7 on 2020-07-01 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='quiz_taker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
